Repository rclone/rclone, pull requests merged in 2021-04, with the labels that each got.

#5200 selfupdate: dont detect FUSE if build is static
  cmd/cmount/mount.go
  cmd/selfupdate/help.go
  cmd/selfupdate/selfupdate.go
  lib/buildinfo/cmount.go
  lib/buildinfo/tags.go
Labels: Point Release Candidate, bug, good first issue, maintenance

#5201 build: add build tag noselfupdate
  cmd/cmd.go
  cmd/selfupdate/help.go
  cmd/selfupdate/noselfupdate.go
  cmd/selfupdate/selfupdate.go
  cmd/selfupdate/selfupdate_test.go
  cmd/selfupdate/verify.go
  cmd/selfupdate/writable_unix.go
  cmd/selfupdate/writable_unsupported.go
  cmd/selfupdate/writable_windows.go
  cmd/selfupdate_disabled.go
  cmd/selfupdate_enabled.go
  lib/buildinfo/tags.go
Labels: build, enhancement, good first issue

#5204 cmd/version: print os/version, kernel and bitness
  cmd/cmd.go
  cmd/version/version.go
  go.mod
  go.sum
  lib/buildinfo/osversion.go
  lib/buildinfo/osversion_openbsd.go
  lib/buildinfo/osversion_windows.go
Labels: enhancement, maintenance

#5198 sync: don't warn about --no-traverse when --files-from is set
  fs/sync/sync.go
Labels: UX, enhancement

#5219 backend/ftp: fix implicit TLS after PR #4266
  backend/ftp/ftp.go
Labels: Point Release Candidate, Remote: FTP, bug

#5230 Silence the progress output with curl requests
  docs/content/install.sh
Labels: enhancement, maintenance

#5215 Add --size flag for rclone rcat - closes #4403
  cmd/rcat/rcat.go
Labels: UX, enhancement

#5240 Don't Open Browser when Google Drive Service Account Credentials Specified
  backend/drive/drive.go
Labels: configuration, enhancement

#5235 Platform independent memory-only config option to be used in build
  docs/content/docs.md
  fs/config/config.go
Labels: build, configuration

#5261 GitHub issue templates: Add GH Etiquette.
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Feature.md
Labels: enhancement

#5140 add --s3-no-head-object
  backend/s3/s3.go
Labels: Remote: S3, enhancement
