Repository rclone/rclone, pull requests merged in 2021-05, with the labels that each got.

#5296 http: clean up Bind to better use middleware
  cmd/serve/http/http.go
  cmd/serve/http/http_test.go
Labels: Servers (any), refactoring

#5317 vfs: avoid unnecessary subdir in cache path
  fs/fs.go
Labels: VFS / mount

#5324 selfupdate: fix archive name on macos
  cmd/selfupdate/selfupdate.go
Labels: bug, maintenance

#5325 dropbox: improve the "own App IP" instructions
  docs/content/dropbox.md
Labels: Remote: Dropbox, doc fix

#5326 some improvement about documentation related to --disable
  docs/content/flags.md
  fs/config/configflags/configflags.go
Labels: UX, doc fix

#5336 dbhashsum: drop command deprecated a year ago - #4837
  cmd/all/all.go
  cmd/dbhashsum/dbhashsum.go
  cmd/hashsum/hashsum.go
Labels: maintenance

#5339 fs/hash: align hashsum names and update documentation
  backend/dropbox/dropbox.go
  backend/mailru/mailru.go
  backend/onedrive/onedrive.go
  cmd/hashsum/hashsum.go
  docs/content/commands/rclone_hashsum.md
  docs/content/flags.md
  fs/hash/hash.go
  fs/hash/hash_test.go
  fs/operations/operations_test.go
  fs/options_test.go
Labels: UX, hashing

#5351 vfs: fix that umask option cannot be set as environment variable
  vfs/vfsflags/vfsflags_unix.go
Labels: OS: Unix, VFS / mount, bug

#5372 jottacloud: fix invalid url in output from link command
  backend/jottacloud/jottacloud.go
Labels: Remote: Jottacloud, bug
