Repository rclone/rclone, pull requests merged in 2024-06, with the labels that each got.

#7885 Make BrowseMetadata response of serve dlna more compliant - fixes #7883
  cmd/serve/dlna/cds.go
Labels: Serving

#7874 s3: Add Magalu S3 Object Storage as provider
  README.md
  backend/s3/s3.go
  docs/content/_index.md
  docs/content/s3.md
Labels: Remote: S3

#7906 jottacloud: set metadata on server side copy and move - fixes #7900
  backend/jottacloud/jottacloud.go
Labels: Remote: Jottacloud, metadata

#7908 `s3`: fix 405 error on `HEAD` for delete marker with `versionId`
  backend/s3/s3.go
Labels: bug, Remote: S3
